def add_edge(g):
    g.add_Vertex("Ferozewala")
    g.add_Vertex("Shahdara")
    g.add_Vertex("Badshahi Mosque")
    g.add_Vertex("Thoker Naiz Baig")
    g.add_Vertex("chung")
    g.add_Vertex("Maraka")
    g.add_Vertex("Valencia")
    g.add_Vertex("DHA")
    g.add_Vertex("Lidher")
    g.add_Vertex("Taij Garh")
    g.add_Vertex("Jallo")
    g.add_Vertex("Paragon City")
    g.add_Vertex("Garhi Shahu")
    g.add_Vertex("Allama Iqbal Town")
    G.add_Vertex("Johar Town")
    G.add_Vertex("TownShip")
    G.add_Vertex("Wapda Town")
    G.add_Vertex("Kahna")
    g.add_edge("Ferozewala", "Shahdara", 2.8)
    g.add_edge("Shahdara","Badshahi Mosque", 5)
    g.add_edge("Badshahi Mosque","Thoker Naiz Baig",23)
    g.add_edge("Thoker Naiz Baig","chung",12)
    g.add_edge("chung","Maraka",8)
    g.add_edge("Maraka","Valencia",4)
    g.add_edge("DHA","Lidher",7 )
    g.add_edge("Badshahi Mosque","Taij Garh",19 )
    g.add_edge("Jallo","Taij Garh" ,7 )
    g.add_edge("Taij Garh" , "Paragon City", 13)
    g.add_edge("Paragon City","DHA", 12 )
    g.add_edge("Badshahi Mosque","Garhi Shahu" ,5)
    g.add_edge("Garhi Shahu","Allama Iqbal Town",12 )
    g.add_edge("Allama Iqbal Town","Johar Town",6.5 )
    g.add_edge("Johar Town","TownShip",7.8 )
    g.add_edge("Johar Town","Wapda Town",5.7 )
    g.add_edge("Wapda Town","Thoker Naiz Baig",18 )
    g.add_edge("Wapda Town","Valencia",4 )
    g.add_edge("Wapda Town","TownShip",8 )
    g.add_edge("Valencia","Kahna",18.4 )
    g.add_edge("Kahna","DHA", 17 )
    g.add_edge("DHA","Lidher" , 7)
    g.add_edge("DHA","Ghari Shahu",13.7 )


